//có 2 kiểu dữ liệu

//(Primitive data) Dữ liệu nguyên thủy:
//Numbers  - Integers, float
//String - Any data under sing quote, double quote or backtick quote
//Booleans - true or false value
//Null - empty value or no value
//Underfined - a declared variable without a value
//Symnol - A unique value that can be generated by Symbol contrustor
//NaN
//Map

//(Non-Primitive data) Dữ liệu không phải nguyên thủy:
//Objects
//Arrays


